# Generated by Django 5.1.1 on 2024-10-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Branches',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
