# Generated by Django 5.1.1 on 2024-10-30 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom_admin.branches'),
        ),
    ]
