# Generated by Django 5.1.1 on 2024-11-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_alter_users_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available')], default=0),
        ),
    ]
