# Generated by Django 5.1.1 on 2024-11-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$BYjuRnUkt2dAAyFFXJOD5M$TTTYdMRyHZLj52ul9/4fBYk7C5Yh3awCWdfq3jMI96o=', max_length=128),
        ),
    ]
