# Generated by Django 5.1.1 on 2024-10-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oshodi', '0003_alter_sales_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
