# Generated by Django 5.1.1 on 2024-10-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='returns',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
