# Generated by Django 5.1.1 on 2024-10-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojota', '0002_remove_sales_total_price_alter_inventory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='orderid',
            field=models.IntegerField(),
        ),
    ]
